# Generated by Django 5.0 on 2023-12-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autho', '0002_rename_phone_user_phone_remove_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('FollowID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('FollowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='autho.user')),
                ('FollowingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationType', models.CharField(max_length=255)),
                ('Notification', models.TextField()),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.ImageField(upload_to='posts/')),
                ('Caption', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(choices=[('Hold', 'Hold'), ('Bought', 'Bought')], max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecobins.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('content_creator', 'Content Creator'), ('customer', 'Customer'), ('waste_disposal_provider', 'Waste Disposal Provider')], max_length=25)),
                ('Address', models.TextField()),
                ('ProfilePic', models.ImageField(upload_to='profile_pics/')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setting1', models.CharField(max_length=255)),
                ('Setting2', models.CharField(max_length=255)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Received', 'Received'), ('Delivered', 'Delivered'), ('Transit', 'Transit'), ('Paid', 'Paid')], max_length=20)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='WasteDisposalProvider',
            fields=[
                ('ProviderID', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessName', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('ServicesOffered', models.TextField()),
                ('ContactInformation', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
                ('ProviderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecobins.wastedisposalprovider')),
            ],
        ),
    ]
